name: Deploy To Development Server

on:
  push:
    branches:
      - development

jobs:

  create-deployment-artifacts:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile CSS and JS
        env:
          CI: false
          REACT_APP_API_BASE_URL: ${{ vars.STAGING_API_BASE_URL }}
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm run build

      - name: Create Deployment Artifact
        run: tar -czf admin-dashboard.tar.gz --exclude=.git --exclude=node_modules --exclude=.env *

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-dashboard
          path: admin-dashboard.tar.gz

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: create-deployment-artifacts

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: admin-dashboard

      - name: Upload To Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_STAGING_SERVER_IP }}
          username: ${{ secrets.DO_STAGING_SERVER_USER }}
          key: ${{ secrets.DO_STAGING_SERVER_SSH_KEY }}
          port: 22
          source: admin-dashboard.tar.gz
          target: /var/www/html/admin-dashboard-artifacts

      - name: Extract Artifact And Copy To Root Directory
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_STAGING_SERVER_IP }}
          username: ${{ secrets.DO_STAGING_SERVER_USER }}
          key: ${{ secrets.DO_STAGING_SERVER_SSH_KEY }}
          script: |
            tar xzf /var/www/html/admin-dashboard-artifacts/admin-dashboard.tar.gz -C /var/www/html/livecode-admin-dashboard
            rm /var/www/html/admin-dashboard-artifacts/admin-dashboard.tar.gz
