name: Deploy to Development Server

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_STAGING_SERVER_SSH_KEY }}

      - name: SSH and Pull Code
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_STAGING_SERVER_IP }}
          username: ${{ secrets.DO_STAGING_SERVER_USER }}
          key: ${{ secrets.DO_STAGING_SERVER_SSH_KEY }}
          script: |
            cd /var/www/html/livecode-admin-dashboard
            git pull origin development
            npm install
            rpm run build
